---
deployment:
  tasks:
    - export DEPLOYPATH=/home/wimsaioc/fredwim.site/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp cv.html $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R project $DEPLOYPATH
